version: '3'
services:
    mysql:
        container_name: 'cactus-educa-mysql'
        image: mysql:latest
        ports:
            - 33066:3306
        environment:
            MYSQL_DATABASE: root
            MYSQL_ROOT_PASSWORD: password
